# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

# Keep rules for Kotlinx Serialization
-keepclassmembers class **.*$$serializer { *; }
-keep class * implements kotlinx.serialization.Serializer
-keep class **.*$$serializer

-keepclasseswithmembers class * {
    @kotlinx.serialization.Serializable <methods>;
}

-keep class kotlin.Metadata { *; }

# Keep all classes and members generated by Protocol Buffers
-keep class com.google.protobuf.** { *; }
-keep class * extends com.google.protobuf.GeneratedMessageLite { *; }
-keep class * extends com.google.protobuf.GeneratedMessageLite$Builder { *; }

# Keep specific members for Kotlin-generated classes from protobuf-lite
-keepclassmembers class **_Kt$* {
    public static ** get*();
}

# Don't warn about missing classes or members from Protocol Buffers
-dontwarn com.google.protobuf.**

# Keep router class names for navigation
-keepnames class com.turisla.hellopocket.router.** { *; }
